### ISSUE TITLE
Can't work with tabview with floating action button

### ISSUE THREAD

**Issue by ethanlee27** [minaxorg/flutter_intro#19] opened 2024-05-08 07:17 UTC
hi, when I start to run this page with 3 tabs and has it's floating action button(FAB), and I want to intro each FAB when tab was changed.
But I found when I press FAB to start intro, only tab 1 will show intro effect.
Then switch to tab 2 or tab 3, the FAB not display intro effect.

Below is my sample code, please help me.
Thank you very much.

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'My App',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        home: Intro(
          padding: EdgeInsets.zero,
          borderRadius: const BorderRadius.all(Radius.circular(4)),
          maskColor: const Color.fromRGBO(0, 0, 0, .6),
          child: const MyHomePage(title: 'Flutter Demo Home Page'),
        ));
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  List tabs = ["Tab1", "Tab2", "Tab3"];
  int _tabIndex = 0;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: tabs.length, vsync: this);

    _tabController.addListener(() {
      var index = _tabController.index;
      switch (index) {
        case 0:
          setState(() {
            _tabIndex = 0;
          });
          break;
        case 1:
          setState(() {
            _tabIndex = 1;
          });
          break;
        case 2:
          setState(() {
            _tabIndex = 2;
          });
          break;
        default:
          break;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("App Name"),
        bottom: TabBar(
          controller: _tabController,
          tabs: tabs.map((e) => Tab(text: e)).toList(),
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: tabs.map((e) {
          return KeepAliveWrapper(
            child: Container(
              alignment: Alignment.center,
              child: Text(e, textScaleFactor: 5),
            ),
          );
        }).toList(),
      ),
      floatingActionButton: _buildFab(),
    );
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  Widget _buildFab() {
    return IntroStepBuilder(
      order: 1,
      group: _getGroupName(),
      text: 'page: $_tabIndex',
      builder: (context, key) => FloatingActionButton(
          key: key,
          backgroundColor: _getBgColor(),
          onPressed: () {
            Intro.of(context).start(group: _getGroupName());
          },
          child: Icon(_getIconData(), color: Colors.white, size: 25)),
    );
  }

  String _getGroupName() {
    String name = 'group$_tabIndex';
    print('group name:$name');
    return name;
  }

  Color _getBgColor() {
    switch (_tabIndex) {
      case 0:
        return Colors.green;
      case 1:
        return Colors.red;
      case 2:
        return Colors.blue;
      default:
        return Colors.black;
    }
  }

  IconData _getIconData() {
    switch (_tabIndex) {
      case 0:
        return Icons.add;
      case 1:
        return Icons.access_time;
      case 2:
        return Icons.add_a_photo;
      default:
        return Icons.abc_sharp;
    }
  }
}
```

**Comment by hellohejinyu** [comment] 2024-05-08 08:40
Thank you for providing such a detailed reproduction code. It has been confirmed to be a bug. The problem is that you dynamically returned the IntroStepBuilder in the method. This problem has been fixed in version `3.2.1`. Thank you.


https://github.com/minaxorg/flutter_intro/assets/8766034/e51879d1-5865-4580-8628-61056201a06f

**Closed by hellohejinyu** 2024-05-08 08:40 UTC

**Comment by hellohejinyu** [comment] 2024-05-08 08:46
In addition, the current dynamic generation of StepBuilder through methods will cause a set of guidance steps to be executed multiple times. In your example, assume that the boot steps in group0 have been executed, and then when you switch back to group0 from the tab, you will find that you can execute it again when you call start. This is because StepBuilder is added to the boot list again. So you need to record whether a certain group is guided. This problem will be solved later when I have free time.😊

**Comment by ethanlee27** [comment] 2024-05-09 02:37
@hellohejinyu 
Thanks a lot you fixed it so quickly.
And the problem you describe above, I can record it with shared preference to prevent it guide again.
